name = "MultipleScattering"
uuid = "80a8ab25-5750-5d93-a6d7-4adc97cdd5fb"
author = ["Artur L. Gower", "Jonathan Deakin"]
version = "0.1.20"

[deps]
GSL = "92c85e6c-cbff-5e0c-80f7-495c94daaecd"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
WignerSymbols = "9f57e263-0b3d-5e2e-b1be-24f2bb48858b"

[compat]
GSL = "^0.6, ^0.7, ^0.8, ^0.9, 1.0"
OffsetArrays = "^0.23, 1"
ProgressMeter = "^1.3"
RecipesBase = "1.0"
SpecialFunctions = "^0.7, ^0.8, ^0.9, 0.10, 1, 2"
StaticArrays = "^0.8, ^0.9, ^0.10, ^0.11, 0.12, ^1"
Statistics = "1"
WignerSymbols = "^1, 2"
julia = "1"

[extras]
GSL = "92c85e6c-cbff-5e0c-80f7-495c94daaecd"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Plots", "GSL", "SpecialFunctions"]
